<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Bidang extends Seeder
{
    public function run(): void
    {
        DB::table('bidang')->insert([
            ['id_bidang' => 1, 'nama_bidang' => 'Full Stack Development'],
            ['id_bidang' => 2, 'nama_bidang' => 'Front End Development'],
            ['id_bidang' => 3, 'nama_bidang' => 'Back End Development'],
            ['id_bidang' => 4, 'nama_bidang' => 'Mobile Engineering'],
            ['id_bidang' => 5, 'nama_bidang' => 'Progressive Web App (PWA)'],
            ['id_bidang' => 6, 'nama_bidang' => 'Single Page Application (SPA)'],
            ['id_bidang' => 7, 'nama_bidang' => 'Serverless Architecture'],
            ['id_bidang' => 8, 'nama_bidang' => 'Cloud Security'],
            ['id_bidang' => 9, 'nama_bidang' => 'Hybrid Cloud Management'],
            ['id_bidang' => 10, 'nama_bidang' => 'Private Cloud Infrastructure'],
            ['id_bidang' => 11, 'nama_bidang' => 'Public Cloud Infrastructure'],
            ['id_bidang' => 12, 'nama_bidang' => 'Containerization (Docker, Kubernetes)'],
            ['id_bidang' => 13, 'nama_bidang' => 'Microservices Architecture'],
            ['id_bidang' => 14, 'nama_bidang' => 'IT Operations'],
            ['id_bidang' => 15, 'nama_bidang' => 'Data Governance'],
            ['id_bidang' => 16, 'nama_bidang' => 'Data Warehousing'],
            ['id_bidang' => 17, 'nama_bidang' => 'Data Lake'],
            ['id_bidang' => 18, 'nama_bidang' => 'Data Visualization'],
            ['id_bidang' => 19, 'nama_bidang' => 'Business Process Automation (BPA)'],
            ['id_bidang' => 20, 'nama_bidang' => 'Intelligent Automation'],
            ['id_bidang' => 21, 'nama_bidang' => 'Robotic Process Automation (RPA)'],
            ['id_bidang' => 22, 'nama_bidang' => 'Smart City Technology'],
            ['id_bidang' => 23, 'nama_bidang' => 'Smart Agriculture Technology'],
            ['id_bidang' => 24, 'nama_bidang' => 'Smart Manufacturing'],
            ['id_bidang' => 25, 'nama_bidang' => 'Industrial Internet of Things (IIoT)'],
            ['id_bidang' => 26, 'nama_bidang' => 'Wireless Sensor Network'],
            ['id_bidang' => 27, 'nama_bidang' => 'Satellite Communication Systems'],
            ['id_bidang' => 28, 'nama_bidang' => 'Information Retrieval Systems'],
            ['id_bidang' => 29, 'nama_bidang' => 'Search Engine Technology'],
            ['id_bidang' => 30, 'nama_bidang' => 'Crowdsourcing Technology'],
            ['id_bidang' => 31, 'nama_bidang' => 'Recommendation System'],
            ['id_bidang' => 32, 'nama_bidang' => 'Sentiment Analysis'],
            ['id_bidang' => 33, 'nama_bidang' => 'Speech Recognition Technology'],
            ['id_bidang' => 34, 'nama_bidang' => 'Autonomous Systems'],
            ['id_bidang' => 35, 'nama_bidang' => 'Drone Technology'],
            ['id_bidang' => 36, 'nama_bidang' => 'Space Technology and Informatics'],
            ['id_bidang' => 37, 'nama_bidang' => 'Digital Identity Management'],
            ['id_bidang' => 38, 'nama_bidang' => 'Privacy Engineering'],
            ['id_bidang' => 39, 'nama_bidang' => 'Zero Trust Security'],
            ['id_bidang' => 40, 'nama_bidang' => 'Ethical Hacking'],
            ['id_bidang' => 41, 'nama_bidang' => 'Cyber Threat Intelligence'],
            ['id_bidang' => 42, 'nama_bidang' => 'Cryptography'],
            ['id_bidang' => 43, 'nama_bidang' => 'Secure Software Development'],
            ['id_bidang' => 44, 'nama_bidang' => 'Digital Twin Technology'],
            ['id_bidang' => 45, 'nama_bidang' => 'Software Architecture'],
            ['id_bidang' => 46, 'nama_bidang' => 'Hardware Engineering'],
            ['id_bidang' => 47, 'nama_bidang' => 'ASIC and FPGA Design'],
            ['id_bidang' => 48, 'nama_bidang' => 'Low-Level Programming'],
            ['id_bidang' => 49, 'nama_bidang' => 'Firmware Development'],
            ['id_bidang' => 50, 'nama_bidang' => 'Compiler Design'],
            ['id_bidang' => 51, 'nama_bidang' => 'Operating System Development'],
            ['id_bidang' => 52, 'nama_bidang' => 'Telecommunications Engineering'],
            ['id_bidang' => 53, 'nama_bidang' => '5G Network Technology'],
            ['id_bidang' => 54, 'nama_bidang' => 'Network Automation'],
            ['id_bidang' => 55, 'nama_bidang' => 'Network Security Monitoring'],
            ['id_bidang' => 56, 'nama_bidang' => 'SD-WAN Technology'],
            ['id_bidang' => 57, 'nama_bidang' => 'Network Virtualization'],
            ['id_bidang' => 58, 'nama_bidang' => 'VoIP and Communication Systems'],
            ['id_bidang' => 59, 'nama_bidang' => 'Real-Time Systems'],
            ['id_bidang' => 60, 'nama_bidang' => 'Embedded AI Systems'],
            ['id_bidang' => 61, 'nama_bidang' => 'Digital Circuit Design'],
            ['id_bidang' => 62, 'nama_bidang' => 'Analog and Mixed Signal Design'],
            ['id_bidang' => 63, 'nama_bidang' => 'Bioelectronic Devices'],
            ['id_bidang' => 64, 'nama_bidang' => 'Medical Device Software'],
            ['id_bidang' => 65, 'nama_bidang' => 'E-Health Systems'],
            ['id_bidang' => 66, 'nama_bidang' => 'Smart Home Systems'],
            ['id_bidang' => 67, 'nama_bidang' => 'Home Automation'],
            ['id_bidang' => 68, 'nama_bidang' => 'IT Support Services'],
            ['id_bidang' => 69, 'nama_bidang' => 'End-User Computing'],
            ['id_bidang' => 70, 'nama_bidang' => 'Knowledge Management Systems'],
            ['id_bidang' => 71, 'nama_bidang' => 'Online Collaboration Tools'],
            ['id_bidang' => 72, 'nama_bidang' => 'Remote Work Technology'],
            ['id_bidang' => 73, 'nama_bidang' => 'E-Learning Technology'],
            ['id_bidang' => 74, 'nama_bidang' => 'Learning Management System (LMS)'],
            ['id_bidang' => 75, 'nama_bidang' => 'Digital Library Systems'],
            ['id_bidang' => 76, 'nama_bidang' => 'Archival Information Systems'],
            ['id_bidang' => 77, 'nama_bidang' => 'Digital Publishing Systems'],
            ['id_bidang' => 78, 'nama_bidang' => 'Streaming Platform Technology'],
            ['id_bidang' => 79, 'nama_bidang' => 'Content Delivery Networks (CDN)'],
            ['id_bidang' => 80, 'nama_bidang' => 'Digital Content Management'],
            ['id_bidang' => 81, 'nama_bidang' => 'Interactive Media Technology'],
            ['id_bidang' => 82, 'nama_bidang' => 'Game Engine Development'],
            ['id_bidang' => 83, 'nama_bidang' => 'Virtual Production Technology'],
            ['id_bidang' => 84, 'nama_bidang' => 'Live Streaming Infrastructure'],
            ['id_bidang' => 85, 'nama_bidang' => 'Digital Signage Systems'],
            ['id_bidang' => 86, 'nama_bidang' => 'Mobile Payment Systems'],
            ['id_bidang' => 87, 'nama_bidang' => 'Cryptocurrency Technology'],
            ['id_bidang' => 88, 'nama_bidang' => 'Smart Contract Development'],
            ['id_bidang' => 89, 'nama_bidang' => 'Decentralized Finance (DeFi)'],
            ['id_bidang' => 90, 'nama_bidang' => 'Digital Asset Management'],
            ['id_bidang' => 91, 'nama_bidang' => 'NFT Platforms'],
            ['id_bidang' => 92, 'nama_bidang' => 'Cyber Law and Policy'],
            ['id_bidang' => 93, 'nama_bidang' => 'Digital Ethics and Responsibility'],
            ['id_bidang' => 94, 'nama_bidang' => 'Open Data Systems'],
            ['id_bidang' => 95, 'nama_bidang' => 'Digital Forensics'],
            ['id_bidang' => 96, 'nama_bidang' => 'Disaster Recovery Planning'],
            ['id_bidang' => 97, 'nama_bidang' => 'Business Continuity Technology'],
            ['id_bidang' => 98, 'nama_bidang' => 'AI Model Deployment'],
            ['id_bidang' => 99, 'nama_bidang' => 'ML Ops'],
            ['id_bidang' => 100, 'nama_bidang' => 'DataOps'],
            ['id_bidang' => 101, 'nama_bidang' => 'Observability and Monitoring'],
            ['id_bidang' => 102, 'nama_bidang' => 'Site Reliability Engineering (SRE)'],
            ['id_bidang' => 103, 'nama_bidang' => 'Digital Inclusion Technology'],
            ['id_bidang' => 104, 'nama_bidang' => 'Accessibility Technology'],
            ['id_bidang' => 105, 'nama_bidang' => 'Sustainable Computing'],
            ['id_bidang' => 106, 'nama_bidang' => 'Tech Entrepreneurship'],
        ]);
    }
}