<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Keahlian extends Seeder
{
    public function run(): void
    {
        DB::table('keahlian')->insert([
            ['id_keahlian' => 1, 'nama_keahlian' => 'Pemrograman Web'],
            ['id_keahlian' => 2, 'nama_keahlian' => 'Pemrograman Mobile'],
            ['id_keahlian' => 3, 'nama_keahlian' => 'Pemrograman Desktop'],
            ['id_keahlian' => 4, 'nama_keahlian' => 'HTML'],
            ['id_keahlian' => 5, 'nama_keahlian' => 'CSS'],
            ['id_keahlian' => 6, 'nama_keahlian' => 'SCSS'],
            ['id_keahlian' => 7, 'nama_keahlian' => 'Bootstrap'],
            ['id_keahlian' => 8, 'nama_keahlian' => 'Tailwind CSS'],
            ['id_keahlian' => 9, 'nama_keahlian' => 'JavaScript'],
            ['id_keahlian' => 10, 'nama_keahlian' => 'TypeScript'],
            ['id_keahlian' => 11, 'nama_keahlian' => 'jQuery'],
            ['id_keahlian' => 12, 'nama_keahlian' => 'PHP'],
            ['id_keahlian' => 13, 'nama_keahlian' => 'Laravel'],
            ['id_keahlian' => 14, 'nama_keahlian' => 'Livewire'],
            ['id_keahlian' => 15, 'nama_keahlian' => 'CodeIgniter'],
            ['id_keahlian' => 16, 'nama_keahlian' => 'Python'],
            ['id_keahlian' => 17, 'nama_keahlian' => 'Django'],
            ['id_keahlian' => 18, 'nama_keahlian' => 'Flask'],
            ['id_keahlian' => 19, 'nama_keahlian' => 'FastAPI'],
            ['id_keahlian' => 20, 'nama_keahlian' => 'Java'],
            ['id_keahlian' => 21, 'nama_keahlian' => 'Spring Boot'],
            ['id_keahlian' => 22, 'nama_keahlian' => 'Kotlin'],
            ['id_keahlian' => 23, 'nama_keahlian' => 'C'],
            ['id_keahlian' => 24, 'nama_keahlian' => 'C++'],
            ['id_keahlian' => 25, 'nama_keahlian' => 'C#'],
            ['id_keahlian' => 26, 'nama_keahlian' => '.NET Core'],
            ['id_keahlian' => 27, 'nama_keahlian' => 'VB.NET'],
            ['id_keahlian' => 28, 'nama_keahlian' => 'Go (Golang)'],
            ['id_keahlian' => 29, 'nama_keahlian' => 'Rust'],
            ['id_keahlian' => 30, 'nama_keahlian' => 'Ruby'],
            ['id_keahlian' => 31, 'nama_keahlian' => 'Ruby on Rails'],
            ['id_keahlian' => 32, 'nama_keahlian' => 'Swift'],
            ['id_keahlian' => 33, 'nama_keahlian' => 'Objective-C'],
            ['id_keahlian' => 34, 'nama_keahlian' => 'React'],
            ['id_keahlian' => 35, 'nama_keahlian' => 'Vue.js'],
            ['id_keahlian' => 36, 'nama_keahlian' => 'Angular'],
            ['id_keahlian' => 37, 'nama_keahlian' => 'Next.js'],
            ['id_keahlian' => 38, 'nama_keahlian' => 'Nuxt.js'],
            ['id_keahlian' => 39, 'nama_keahlian' => 'Node.js'],
            ['id_keahlian' => 40, 'nama_keahlian' => 'Express.js'],
            ['id_keahlian' => 41, 'nama_keahlian' => 'NestJS'],
            ['id_keahlian' => 42, 'nama_keahlian' => 'GraphQL'],
            ['id_keahlian' => 43, 'nama_keahlian' => 'REST API'],
            ['id_keahlian' => 44, 'nama_keahlian' => 'JSON'],
            ['id_keahlian' => 45, 'nama_keahlian' => 'AJAX'],
            ['id_keahlian' => 46, 'nama_keahlian' => 'WebSocket'],
            ['id_keahlian' => 47, 'nama_keahlian' => 'MySQL'],
            ['id_keahlian' => 48, 'nama_keahlian' => 'PostgreSQL'],
            ['id_keahlian' => 49, 'nama_keahlian' => 'SQLite'],
            ['id_keahlian' => 50, 'nama_keahlian' => 'MongoDB'],
            ['id_keahlian' => 51, 'nama_keahlian' => 'Redis'],
            ['id_keahlian' => 52, 'nama_keahlian' => 'Firebase'],
            ['id_keahlian' => 53, 'nama_keahlian' => 'Supabase'],
            ['id_keahlian' => 54, 'nama_keahlian' => 'Oracle Database'],
            ['id_keahlian' => 55, 'nama_keahlian' => 'SQL Server'],
            ['id_keahlian' => 56, 'nama_keahlian' => 'Database Design'],
            ['id_keahlian' => 57, 'nama_keahlian' => 'ERD Modeling'],
            ['id_keahlian' => 58, 'nama_keahlian' => 'Data Warehouse'],
            ['id_keahlian' => 59, 'nama_keahlian' => 'ETL Process'],
            ['id_keahlian' => 60, 'nama_keahlian' => 'Data Mining'],
            ['id_keahlian' => 61, 'nama_keahlian' => 'Machine Learning'],
            ['id_keahlian' => 62, 'nama_keahlian' => 'Deep Learning'],
            ['id_keahlian' => 63, 'nama_keahlian' => 'NLP (Natural Language Processing)'],
            ['id_keahlian' => 64, 'nama_keahlian' => 'Computer Vision'],
            ['id_keahlian' => 65, 'nama_keahlian' => 'TensorFlow'],
            ['id_keahlian' => 66, 'nama_keahlian' => 'Keras'],
            ['id_keahlian' => 67, 'nama_keahlian' => 'PyTorch'],
            ['id_keahlian' => 68, 'nama_keahlian' => 'Scikit-learn'],
            ['id_keahlian' => 69, 'nama_keahlian' => 'OpenCV'],
            ['id_keahlian' => 70, 'nama_keahlian' => 'Data Analysis'],
            ['id_keahlian' => 71, 'nama_keahlian' => 'Pandas'],
            ['id_keahlian' => 72, 'nama_keahlian' => 'NumPy'],
            ['id_keahlian' => 73, 'nama_keahlian' => 'Matplotlib'],
            ['id_keahlian' => 74, 'nama_keahlian' => 'Seaborn'],
            ['id_keahlian' => 75, 'nama_keahlian' => 'Power BI'],
            ['id_keahlian' => 76, 'nama_keahlian' => 'Tableau'],
            ['id_keahlian' => 77, 'nama_keahlian' => 'Excel Advanced'],
            ['id_keahlian' => 78, 'nama_keahlian' => 'Big Data'],
            ['id_keahlian' => 79, 'nama_keahlian' => 'Hadoop'],
            ['id_keahlian' => 80, 'nama_keahlian' => 'Apache Spark'],
            ['id_keahlian' => 81, 'nama_keahlian' => 'Cloud Computing'],
            ['id_keahlian' => 82, 'nama_keahlian' => 'AWS'],
            ['id_keahlian' => 83, 'nama_keahlian' => 'Microsoft Azure'],
            ['id_keahlian' => 84, 'nama_keahlian' => 'Google Cloud Platform'],
            ['id_keahlian' => 85, 'nama_keahlian' => 'Docker'],
            ['id_keahlian' => 86, 'nama_keahlian' => 'Kubernetes'],
            ['id_keahlian' => 87, 'nama_keahlian' => 'CI/CD'],
            ['id_keahlian' => 88, 'nama_keahlian' => 'Git'],
            ['id_keahlian' => 89, 'nama_keahlian' => 'GitHub'],
            ['id_keahlian' => 90, 'nama_keahlian' => 'GitLab'],
            ['id_keahlian' => 91, 'nama_keahlian' => 'Bitbucket'],
            ['id_keahlian' => 92, 'nama_keahlian' => 'Linux Administration'],
            ['id_keahlian' => 93, 'nama_keahlian' => 'Windows Server'],
            ['id_keahlian' => 94, 'nama_keahlian' => 'Bash Scripting'],
            ['id_keahlian' => 95, 'nama_keahlian' => 'DevOps'],
            ['id_keahlian' => 96, 'nama_keahlian' => 'Terraform'],
            ['id_keahlian' => 97, 'nama_keahlian' => 'Ansible'],
            ['id_keahlian' => 98, 'nama_keahlian' => 'Jenkins'],
            ['id_keahlian' => 99, 'nama_keahlian' => 'Cyber Security'],
            ['id_keahlian' => 100, 'nama_keahlian' => 'Network Security'],
            ['id_keahlian' => 101, 'nama_keahlian' => 'Penetration Testing'],
            ['id_keahlian' => 102, 'nama_keahlian' => 'Kali Linux'],
            ['id_keahlian' => 103, 'nama_keahlian' => 'Metasploit'],
            ['id_keahlian' => 104, 'nama_keahlian' => 'Wireshark'],
            ['id_keahlian' => 105, 'nama_keahlian' => 'Firewall Configuration'],
            ['id_keahlian' => 106, 'nama_keahlian' => 'Cisco Packet Tracer'],
            ['id_keahlian' => 107, 'nama_keahlian' => 'MikroTik Routing'],
            ['id_keahlian' => 108, 'nama_keahlian' => 'Active Directory'],
            ['id_keahlian' => 109, 'nama_keahlian' => 'Virtualisasi'],
            ['id_keahlian' => 110, 'nama_keahlian' => 'VMware'],
            ['id_keahlian' => 111, 'nama_keahlian' => 'VirtualBox'],
            ['id_keahlian' => 112, 'nama_keahlian' => 'UI/UX Design'],
            ['id_keahlian' => 113, 'nama_keahlian' => 'Figma'],
            ['id_keahlian' => 114, 'nama_keahlian' => 'Adobe XD'],
            ['id_keahlian' => 115, 'nama_keahlian' => 'Design Thinking'],
            ['id_keahlian' => 116, 'nama_keahlian' => 'Game Development'],
            ['id_keahlian' => 117, 'nama_keahlian' => 'Unity'],
            ['id_keahlian' => 118, 'nama_keahlian' => 'Unreal Engine'],
            ['id_keahlian' => 119, 'nama_keahlian' => 'Blender'],
            ['id_keahlian' => 120, 'nama_keahlian' => 'AR/VR Development'],
            ['id_keahlian' => 121, 'nama_keahlian' => 'Blockchain Development'],
            ['id_keahlian' => 122, 'nama_keahlian' => 'Solidity'],
            ['id_keahlian' => 123, 'nama_keahlian' => 'Smart Contracts'],
            ['id_keahlian' => 124, 'nama_keahlian' => 'Web3.js'],
            ['id_keahlian' => 125, 'nama_keahlian' => 'Project Management'],
            ['id_keahlian' => 126, 'nama_keahlian' => 'Agile'],
            ['id_keahlian' => 127, 'nama_keahlian' => 'Scrum'],
            ['id_keahlian' => 128, 'nama_keahlian' => 'Trello'],
            ['id_keahlian' => 129, 'nama_keahlian' => 'Jira'],
            ['id_keahlian' => 130, 'nama_keahlian' => 'Notion'],
            ['id_keahlian' => 131, 'nama_keahlian' => 'SQA (Software Quality Assurance)'],
            ['id_keahlian' => 132, 'nama_keahlian' => 'Manual Testing'],
            ['id_keahlian' => 133, 'nama_keahlian' => 'Automation Testing'],
            ['id_keahlian' => 134, 'nama_keahlian' => 'Selenium'],
            ['id_keahlian' => 135, 'nama_keahlian' => 'Postman'],
            ['id_keahlian' => 136, 'nama_keahlian' => 'API Testing'],
            ['id_keahlian' => 137, 'nama_keahlian' => 'Penulisan Dokumentasi Teknis'],
        ]);
    }
}