<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Lokasi extends Seeder
{
    public function run(): void
    {
        DB::table('lokasi')->insert([
            ['id_lokasi' => 1, 'nama_lokasi' => 'Ambon'],
            ['id_lokasi' => 2, 'nama_lokasi' => 'Balikpapan'],
            ['id_lokasi' => 3, 'nama_lokasi' => 'Banda Aceh'],
            ['id_lokasi' => 4, 'nama_lokasi' => 'Bandar Lampung'],
            ['id_lokasi' => 5, 'nama_lokasi' => 'Bandung'],
            ['id_lokasi' => 6, 'nama_lokasi' => 'Banjar'],
            ['id_lokasi' => 7, 'nama_lokasi' => 'Banjarmasin'],
            ['id_lokasi' => 8, 'nama_lokasi' => 'Banjarbaru'],
            ['id_lokasi' => 9, 'nama_lokasi' => 'Batu'],
            ['id_lokasi' => 10, 'nama_lokasi' => 'Bekasi'],
            ['id_lokasi' => 11, 'nama_lokasi' => 'Bengkalis'],
            ['id_lokasi' => 12, 'nama_lokasi' => 'Bengkulu'],
            ['id_lokasi' => 13, 'nama_lokasi' => 'Binjai'],
            ['id_lokasi' => 14, 'nama_lokasi' => 'Bitung'],
            ['id_lokasi' => 15, 'nama_lokasi' => 'Blitar'],
            ['id_lokasi' => 16, 'nama_lokasi' => 'Bogor'],
            ['id_lokasi' => 17, 'nama_lokasi' => 'Bontang'],
            ['id_lokasi' => 18, 'nama_lokasi' => 'Bukittinggi'],
            ['id_lokasi' => 19, 'nama_lokasi' => 'Cilegon'],
            ['id_lokasi' => 20, 'nama_lokasi' => 'Cimahi'],
            ['id_lokasi' => 21, 'nama_lokasi' => 'Cirebon'],
            ['id_lokasi' => 22, 'nama_lokasi' => 'Denpasar'],
            ['id_lokasi' => 23, 'nama_lokasi' => 'Depok'],
            ['id_lokasi' => 24, 'nama_lokasi' => 'Dumai'],
            ['id_lokasi' => 25, 'nama_lokasi' => 'Gorontalo'],
            ['id_lokasi' => 26, 'nama_lokasi' => 'Gunungsitoli'],
            ['id_lokasi' => 27, 'nama_lokasi' => 'Jakarta'],
            ['id_lokasi' => 28, 'nama_lokasi' => 'Jambi'],
            ['id_lokasi' => 29, 'nama_lokasi' => 'Jayapura'],
            ['id_lokasi' => 30, 'nama_lokasi' => 'Kendari'],
            ['id_lokasi' => 31, 'nama_lokasi' => 'Kotamobagu'],
            ['id_lokasi' => 32, 'nama_lokasi' => 'Kupang'],
            ['id_lokasi' => 33, 'nama_lokasi' => 'Langsa'],
            ['id_lokasi' => 34, 'nama_lokasi' => 'Lhokseumawe'],
            ['id_lokasi' => 35, 'nama_lokasi' => 'Lubuklinggau'],
            ['id_lokasi' => 36, 'nama_lokasi' => 'Madiun'],
            ['id_lokasi' => 37, 'nama_lokasi' => 'Magelang'],
            ['id_lokasi' => 38, 'nama_lokasi' => 'Makassar'],
            ['id_lokasi' => 39, 'nama_lokasi' => 'Malang'],
            ['id_lokasi' => 40, 'nama_lokasi' => 'Manado'],
            ['id_lokasi' => 41, 'nama_lokasi' => 'Mataram'],
            ['id_lokasi' => 42, 'nama_lokasi' => 'Medan'],
            ['id_lokasi' => 43, 'nama_lokasi' => 'Metro'],
            ['id_lokasi' => 44, 'nama_lokasi' => 'Mojokerto'],
            ['id_lokasi' => 45, 'nama_lokasi' => 'Padang'],
            ['id_lokasi' => 46, 'nama_lokasi' => 'Padang Sidempuan'],
            ['id_lokasi' => 47, 'nama_lokasi' => 'Palangkaraya'],
            ['id_lokasi' => 48, 'nama_lokasi' => 'Palembang'],
            ['id_lokasi' => 49, 'nama_lokasi' => 'Palopo'],
            ['id_lokasi' => 50, 'nama_lokasi' => 'Palu'],
            ['id_lokasi' => 51, 'nama_lokasi' => 'Pangkal Pinang'],
            ['id_lokasi' => 52, 'nama_lokasi' => 'Parepare'],
            ['id_lokasi' => 53, 'nama_lokasi' => 'Pasuruan'],
            ['id_lokasi' => 54, 'nama_lokasi' => 'Pekanbaru'],
            ['id_lokasi' => 55, 'nama_lokasi' => 'Pelabuhan Ratu'],
            ['id_lokasi' => 56, 'nama_lokasi' => 'Pemalang'],
            ['id_lokasi' => 57, 'nama_lokasi' => 'Pematangsiantar'],
            ['id_lokasi' => 58, 'nama_lokasi' => 'Pontianak'],
            ['id_lokasi' => 59, 'nama_lokasi' => 'Prabumulih'],
            ['id_lokasi' => 60, 'nama_lokasi' => 'Probolinggo'],
            ['id_lokasi' => 61, 'nama_lokasi' => 'Sabang'],
            ['id_lokasi' => 62, 'nama_lokasi' => 'Salatiga'],
            ['id_lokasi' => 63, 'nama_lokasi' => 'Samarinda'],
            ['id_lokasi' => 68, 'nama_lokasi' => 'Sampit'],
            ['id_lokasi' => 69, 'nama_lokasi' => 'Sanana'],
            ['id_lokasi' => 70, 'nama_lokasi' => 'Sanggau'],
            ['id_lokasi' => 71, 'nama_lokasi' => 'Sarang'],
            ['id_lokasi' => 72, 'nama_lokasi' => 'Sawahlunto'],
            ['id_lokasi' => 73, 'nama_lokasi' => 'Semarang'],
            ['id_lokasi' => 74, 'nama_lokasi' => 'Serang'],
            ['id_lokasi' => 75, 'nama_lokasi' => 'Sibolga'],
            ['id_lokasi' => 76, 'nama_lokasi' => 'Singkawang'],
            ['id_lokasi' => 77, 'nama_lokasi' => 'Sintang'],
            ['id_lokasi' => 78, 'nama_lokasi' => 'Sleman'],
            ['id_lokasi' => 79, 'nama_lokasi' => 'Solok'],
            ['id_lokasi' => 80, 'nama_lokasi' => 'Sorong'],
            ['id_lokasi' => 81, 'nama_lokasi' => 'Subang'],
            ['id_lokasi' => 82, 'nama_lokasi' => 'Subulussalam'],
            ['id_lokasi' => 83, 'nama_lokasi' => 'Sukabumi'],
            ['id_lokasi' => 84, 'nama_lokasi' => 'Sungaipenuh'],
            ['id_lokasi' => 85, 'nama_lokasi' => 'Surabaya'],
            ['id_lokasi' => 86, 'nama_lokasi' => 'Surakarta (Solo)'],
            ['id_lokasi' => 87, 'nama_lokasi' => 'Tangerang'],
            ['id_lokasi' => 88, 'nama_lokasi' => 'Tanjung Pinang'],
            ['id_lokasi' => 89, 'nama_lokasi' => 'Tanjungbalai'],
            ['id_lokasi' => 90, 'nama_lokasi' => 'Tasikmalaya'],
            ['id_lokasi' => 91, 'nama_lokasi' => 'Tidore Kepulauan'],
            ['id_lokasi' => 92, 'nama_lokasi' => 'Ternate'],
            ['id_lokasi' => 93, 'nama_lokasi' => 'Tomohon'],
            ['id_lokasi' => 94, 'nama_lokasi' => 'Tual'],
            ['id_lokasi' => 95, 'nama_lokasi' => 'Wamena'],
            ['id_lokasi' => 96, 'nama_lokasi' => 'Yogyakarta'],
        ]);
    }
}