#!/bin/bash

set -e

if [ ! -d "vendor" ]; then
    composer install --ignore-platform-reqs --no-dev --optimize-autoloader
else
    echo "Folder \"vendor\" sudah ada. Lewati instalasi dependensi PHP."
fi

php artisan migrate --seed

if [ ! -d "node_modules" ]; then
    npm install
else
    echo "Folder \"node_modules\" sudah ada. Lewati instalasi dependensi frontend."
fi

npm update --save